package constants

const APP_NAME = "Zapdos Budget Pro"
const LANGUAGE = "en"

const PLAID_ENV = "PLAID_ENV"
const PLAID_CLIENT_ID = "PLAID_CLIENT_ID"
const PLAID_SECRET = "PLAID_SECRET"
const PLAID_REDIRECT_URI = "PLAID_REDIRECT_URI"
const PLAID_COUNTRY_CODES = "PLAID_COUNTRY_CODES"
const PLAID_PRODUCTS = "PLAID_PRODUCTS"

const HEADER_CLIENT_ID = "PLAID-CLIENT-ID"
const HEADER_SECRET = "PLAID-SECRET"
